app/tilmelding/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField, SelectField, HiddenField, validators, RadioField, FileField, DateField
#from wtforms.fields.html5 import DateField  
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
#from wtforms.ext.sqlalchemy.orm import model_form
#from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask_wtf.file import FileRequired
from werkzeug.utils import secure_filename
#from flask_babel import _, lazy_gettext as _l
#from app.models import User, Konkurrence, Grunddata, Klub, Medlemmer, Deltager, deltager_strak, Baner, PostBaner

class Tilmeld_flere(FlaskForm):
    loeb = StringField('Vaelg_loeb', id='loeb')
    submit_3 = SubmitField('Valg', id='submit_3')

class Tilmeld(FlaskForm):
    navn = StringField('navn')
    klub = StringField('klub')
    email = StringField('email')
    briknummer = StringField('briknummer')
    telefonnummer = StringField('telefonnummer')
    bane = StringField('bane')
    submit_1 = SubmitField('Vælg', id='submit_1')
    #submit_2 = SubmitField('Slut', id='submit_2')

class ret_tilmelding(FlaskForm):
    text = StringField('text')
    submit = SubmitField('submit_1', id='submit_1')

class tilfojGPXfil(FlaskForm):
    #loeb = StringField('skovID', id='loeb')
    loeb = SelectField('Løb:', validators=[DataRequired()], id='loeb')
    navn = StringField('navn')
    klub = StringField('klub')
    bane = StringField('bane')
    GPXfil = FileField()
    submit = SubmitField('Vælg', id='submit')

class alleTilmeldte(FlaskForm):
    loeb = SelectField('Løb:', validators=[DataRequired()], id='loeb')

app/tilmelding/__init__.py
from flask import Blueprint

bp = Blueprint('tilmelding', __name__)

from app.tilmelding import routes

app/tilmelding/routes.py
from email.mime import application
from wsgiref import validate
from click import format_filename
from flask import Flask, Blueprint, render_template, request, flash, redirect, url_for, jsonify, current_app, json, send_from_directory, Response, abort, session
from flask_login import UserMixin, AnonymousUserMixin, login_manager, login_required, logout_user, current_user
#from flask_wtf.csrf  import CSRFProtect
from sqlalchemy import desc
from app.models import Klubber, Post, User, Profile, Tilmeldte, baneresultat, konkurrence_data, Baner, Poster
#from app.resultater.routes import create_map
from app.tilmelding.forms import Tilmeld, Tilmeld_flere, ret_tilmelding, tilfojGPXfil, alleTilmeldte
from app import db
from app.tilmelding import bp
#from app.resultater import bp 
import app
#from app import tilmelding
from sqlalchemy.sql import func
#from sendgrid import SendGridAPIClient
#from sendgrid.helpers.mail import Mail
import os
import tempfile
import shutil
#from . import app
from base64 import b64encode
import base64
import datetime
from datetime import datetime
from datetime import date
#from flask_breadcrumbs import Breadcrumbs, register_breadcrumb, default_breadcrumb_root
#from flask_menu import Menu, register_menu
from pathlib import Path
#from convertpdf import add_kort2, add_billede
from app.tilmelding.helper import bruger_opl, hent_deltagerliste, hent_kort, hent_fuld_deltagerliste, hent_klubber, hent_alle_deltagerliste, hent_pdf, hent_alle_tilmeldte, hent_senst_tilmeldte, hent_alle_navne
from app.tilmelding.gpx_helper import start_gpx, create_map
import folium
from folium import plugins
import gpxpy
import gpxpy.gpx
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import haversine as hs
import lxml
from zipfile import ZipFile
from os import listdir
from dataclasses import dataclass
#hent_tilfojede_kort, sendMails, hent_deltagers_liste, post_picture 
#from sendgrid import SendGridAPIClient
#from sendgrid.helpers.mail import Mail
#from flask_dropzone import Dropzone

UPLOAD_FOLDER = 'uploads'
SENDGRID_API_KEY="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"

def checkDir(check_dir):
    #test = os.path.isdir(check_dir)
    if os.path.isdir(check_dir) != True:
        #shutil.rmtree(check_dir)
        os.mkdir(check_dir)
    #else:
    #    os.mkdir(check_dir)

@bp.route("/slet_tilmeld/", methods=['POST'])
def slet_tilmeld():
    if request.method == "POST":
        pass
    udfyldt_form = request.get_json()
    tilmeldtId_f = int(udfyldt_form['tilmeldtId'])
    loebId_f = int(udfyldt_form['loebId'])
    delt = db.session.query(Tilmeldte).filter(Tilmeldte.id==tilmeldtId_f, Tilmeldte.konkurrence_id==loebId_f).first()
    db.session.delete(delt)
    #db.session.commit()
    return('sussecs!')

@bp.route("/ret_tilmeld/", methods=['POST'])
def ret_tilmeld():
    #valgt_lob = request.form.get('loebhidden')
    udfyldt_form = request.get_json()
    brikOLD_f = udfyldt_form['brikOLD']
    baneOLD_f = udfyldt_form['baneOLD']
    navn_f = udfyldt_form['navn']
    bane_f = udfyldt_form['bane']
    brik_f = udfyldt_form['briknummer']
    telefonnummer_f = udfyldt_form['telefonnummer']
    mail_f = udfyldt_form['email']
    klub_f = udfyldt_form['klub']
    loebId_f = int(udfyldt_form['loebId'])
    profileId_f = int(udfyldt_form['tilmelderId'])
    tilmeldtId_f = int(udfyldt_form['tilmeldtId'])
    if baneOLD_f != bane_f:
        delt = db.session.query(Tilmeldte).filter(Tilmeldte.id==tilmeldtId_f, Tilmeldte.konkurrence_id==loebId_f).first()
        delt.bane = bane_f
        db.session.merge(tilm)
        db.session.commit()
        
    if brikOLD_f != brik_f:
        tilm = db.session.query(Tilmeldte).filter(Tilmeldte.id == tilmeldtId_f).first()
        tilm.brik = brik_f
        db.session.merge(tilm)
        db.session.commit()
    return "succes!"


@bp.route("/add_tilmeld1/", methods=['GET','POST'])
def add_tilmeld1():
    if current_user.is_anonymous == True:
        anonym = True
    else:
        anonym = False
    udfyldt_form = request.get_json()

    navn_f = udfyldt_form['navn']
    bane_f = udfyldt_form['bane']
    brik_f = udfyldt_form['briknummer']
    telefonnummer_f = udfyldt_form['telefonnummer']
    mail_f = udfyldt_form['email']
    klub_f = int(udfyldt_form['klub'])
    loebId_f = int(udfyldt_form['loebId'])
    profileid_f = udfyldt_form['profileid']
    tilmeld_flere_f = int(udfyldt_form['tilmeld_flere'])
    find_baneid = Baner.query.filter(Baner.kokurrence_id==loebId_f, Baner.banenavn==bane_f).first()
    bane_id = find_baneid.id

    if anonym == True and udfyldt_form['profileid'] == "":
        ny_profil = Profile(navn=navn_f, brik=brik_f, email=mail_f, klub_id=klub_f, telefonnummer=telefonnummer_f )
        db.session.add(ny_profil)
        db.session.commit()
        if udfyldt_form['tilmelderId'] == 'Falsk':
            tilmelder = 1
        else:
            tilmelder = 0
        profileid_f = ny_profil.id
        if udfyldt_form['status_profilid'] != '':
            if udfyldt_form['status_profilid'] == 'Falsk':
                tilmelder_id = profileid_f
            else:
                tilmelder_id = udfyldt_form['status_profilid']
        else:
            tilmelder_id = udfyldt_form['tilmelderId']
    
    elif anonym == True and udfyldt_form['status_profilid'] != "Falsk":
        profileid_f = int(profileid_f)
        if udfyldt_form['tilmelderId'] != 'Falsk':
            tilmelder_id = int(udfyldt_form['tilmelderId'])
        else:
            tilmelder_id = int(udfyldt_form['status_profilid'])
        #if udfyldt_form['tilmelderId'] == '':
        #    tilmelder_id = profileid_f
        #else:
        #    tilmelder_id = int(udfyldt_form['tilmelderId'])
        if tilmelder_id == profileid_f:
            #if profileid_f == tilmelder_id:
            tilmelder = 1
        else:
            tilmelder = 0
    
    if anonym == False:
        er_tilmeldt = Tilmeldte.query.filter(Tilmeldte.konkurrence_id==int(udfyldt_form['loebId']), Tilmeldte.profile_id==current_user.id).first()
        tilmelder_id = current_user.id
        if er_tilmeldt == None:
            if profileid_f == '':
                ny_profil = Profile(navn=navn_f, brik=brik_f, email=mail_f, klub_id=klub_f, telefonnummer=telefonnummer_f )
                db.session.add(ny_profil)
                db.session.commit()
                profileid_f = ny_profil.id
                tilmelder = 1
            else:
                profileid_f = current_user.id
                tilmelder = 1
        else:
            tilmelder = 0
            profileid_f = int(profileid_f)
            #profileid_f = int(udfyldt_form['profileid'])

    
    
    #    if tilmeld_flere_f == 1:
    #        if session.get('Tilmelder'):
    #            tilmelder = 0
    #            profil_tilmelder = session['Tilmelder']
    #        else:
    #            session['Tilmelder'] = profileid_f
    #            session['Antal'] = 1
    #            tilmelder = 1
    #            profil_tilmelder = profileid_f
    #    else:
    #        session.pop('Tilmelder')
    #        session.pop('Antal')
    #        tilmelder = 1
    #        profil_tilmelder = profileid_f
    #if udfyldt_form['profileid'] != '':
    #    profileid_f = int(udfyldt_form['profileid'])
    #else:
    #    profileid_f = 0
     
    #if anonym == True and profileid_f == 0:
    #    ny_profil = Profile(navn=navn_f, brik=brik_f, email=mail_f, klub_id=klub_f, telefonnummer=telefonnummer_f )
    #    db.session.add(ny_profil)
    #    db.session.commit()
    #    profileid_f = ny_profil.id
    #elif anonym == True and profileid_f > 0:
    #    if tilmeld_flere_f == 1:
    #        if session.get('Tilmelder'):
    #            tilmelder = 0
    #            profil_tilmelder = session['Tilmelder']
    #        else:
    #            session['Tilmelder'] = profileid_f
    #            session['Antal'] = 1
    #            tilmelder = 1
    #            profil_tilmelder = profileid_f
    #    else:
    #        session.pop('Tilmelder')
    #        session.pop('Antal')
    #        tilmelder = 1
    #        profil_tilmelder = profileid_f

    

    #if session.get('Antal'):
    #    session['Antal'] = session['Antal'] + 1
    
    #session.permanent = False
    
    runner = Tilmeldte(navn=navn_f, tilmelder=tilmelder, bane=bane_f, bane_id=bane_id, klub_id=klub_f, konkurrence_id=loebId_f, profile_id=profileid_f, tilmelder_id=tilmelder_id)
    db.session.add(runner)
    db.session.commit()
    
    tilbage = profileid_f
    flash('Tilmelding gemt', category='success')
    return jsonify(tilbage)

def checkDir(check_dir):
    if os.path.isdir(check_dir) == True:
        shutil.rmtree(check_dir)
        os.mkdir(check_dir)
    else:
        os.mkdir(check_dir)

@bp.route("/Tilmeld/", methods=['POST'])
#@register_breadcrumb(views, '.', 'Tilmeld')
#@register_menu(views, '.', 'Tilmeld')
#@login_required
def tilmeld1():
    #profilpicture = bruger_opl()
    form = Tilmeld
    if current_user.is_anonymous == False:
        bruger_id = current_user.id
    else:
        #bruger_id = int(request.form.get('status_profileid'))
        bruger_id = int(request.form.get('tilmelderId'))
    #profil = Profile.query.filter_by(user_id=current_user.id).first()
    #user = current_user
    #form = Tilmeld
    #test = request.form
    if request.form['submit_2'] == 'slut':
        return redirect(url_for('views.tilmeldte'))
    valgt_lob = request.form.get('loeb')
    if valgt_lob is None:
        valgt_lob = request.form.get('loebhidden')
    #navn_f = request.form.get('navn')
    lob = konkurrence_data.query.filter(konkurrence_data.id==int(valgt_lob)).all()
    lobdato = (lob[0].konkurrenceDatoSlut).strftime("%d-%m-%Y")
    lobtekst = lob[0].konkurrence + " den " + lobdato
    loeb={}
    loeb[lob[0].id] = str(lob[0].konkurrence) + ' ' + str(lob[0].konkurrenceDatoSlut)
    antallob = 1
    
    kortbane, kortene, kort = hent_kort(valgt_lob)

app/templates/tilmelding/_GPX_Postoversigt.html
<link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
<link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-material.css">
<link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />

<div class="masonry-grid-item col pb-1 pb-lg-5">
	<article class="card">
	  	<div class="card-body">
        <form><input type="hidden" name="csrf_token" id="csfr_token" value="{{ csrf_token() }}">
            <input type="hidden" name="banedata_id" id="banedata_id" value="{{ banedata_id }}">
            <h3 class="h4">{{ navn }} - {{ bane }} - Dine stræk. {{ konkurrencenavn }}</h3>
            <div class="card-body">
                <div id="table"></div>
                Selection:
                <span id="selectedRows">
                </span>
                <center>
                <div id="myGrid" style="height:600px; width:100%" class="ag-theme-balham"></div>
                </center>					
            </div>
          </form>
      </div>
	</article>
</div>
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
<!--<script src="https://unpkg.com/@ag-grid-enterprise/all-modules@28.2.1/dist/ag-grid-enterprise.js"></script>-->
<script src="https://cdn.jsdelivr.net/npm/ag-grid-enterprise/dist/ag-grid-enterprise.js"></script>

<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
<script src="{{ url_for('static', filename='js/GPXdata.js') }}"></script>

app/templates/tilmelding/_anonym.html
<div class="masonry-grid-item col pb-2 pb-lg-3">
	<article class="card">
	  <div class="card-body">
        <p class="mb-4">
			<form class="row g-4 needs-validation" method="post" novalidate>
				<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
					<div class="col-sm-6">
						<label for="navn" class="form-label fs-base">Vælg løber der skal rettes</label>
						<select class="form-select form-select-lg" data-customclass="form-select" id="navn" name="navn" required>
							{% if dropdowndata != '' %}
							{% for key1, value1 in dropdowndata.items() %}
								{% if loop.first %}
								<option value= "" disabled selected>Vælg løber</option>
								{% endif %}
								<option value= "{{ key1 }}">{{ value1 }}</option>
							{% endfor %}
							{% endif %}
						</select>
						<div class="invalid-feedback">Vælg et navn fra listen!</div>
					</div>
                </form>
            </p>
        </article>
    </div>
</div>

app/templates/tilmelding/_kort copy.html
{% if erKort %}
<div class="col pb-1 pb-lg-3 mb-6">
	<div class="col-md-12 mb-2">
		<div class="card"></div>
			<div class="card border-light shadow-lg py-3 p-sm-4 p-md-5">
				<h3 class="card-title pb-3 mb-4">Vælg den bane du vil se</h3>
				<ul class="nav nav-tabs" id="myTab" data-bs-tabs="tabs" role="tablist">
				{% for stripkort in kortbane %}
					<li class="nav-item"><a class="nav-link {% if loop.index == 1 %}active{% endif %}" data-bs-toggle="tab" href="#tab{{ loop.index }}" role="tab" aria-controls="tab{{ loop.index }}" aria-selected="false">Bane {{ loop.index }}</a></li>
				{% endfor %}
				</ul>
				<div class="tab-content" id="myTabContent"> 
					{% for dict_item in kort %}
						<div class="tab-pane fade {% if loop.index == 1 %}show active{% endif %}" id="tab{{ loop.index }}" role="tabpanel">
								<img src="{{ url_for('static', filename=dict_item['filen']) }}" class="card-img-top" height="100%" alt="...">
								
							<div align="center">
								<h5 class="card-title">{{ dict_item['banenavn'] }}</h5>
								<p class="card-text">{{ dict_item['beskrivelse'] }}</p>
								<a href="#" id="14" class="btn btn-primary" onclick="reply_click(this)" data-product-name="{{ dict_item['banenavn'] }}">Vælg {{ dict_item['banenavn'] }}</a>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>
{% else %}
<div class="col pb-1 pb-lg-3 mb-6">
	<div class="col-md-12 mb-2">
		<div class="card card-portfolio">
			<h3 class="card-title pb-3 mb-4">Der er ingen kort til download til dette løb. Kort udleveres ved start</h3>
		</div>
	</div>
</div>
{% endif %}

app/templates/tilmelding/_opfylder.html
<div class="masonry-grid-item col pb-2 pb-lg-3">
	<article class="card">
	  	<div class="card-body">
			<h3 class="h4"></h3>
			<p class="mb-4">
				Nunc aliquet scelerisque pellentesque imperdiet tortor elit, dictum. Tristique odio at dignissim viverra aliquet eleifend erat. Tellus, at arcu, egestas praesent.
			</p>
		</div>
	</article>
</div>

app/templates/tilmelding/tilmelding.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block app_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='tab.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/css/autoComplete.01.min.css">
<!--<link rel="stylesheet" href="{{ url_for('static', filename='css/autoComplete.01.css') }}">-->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.4/datatables.min.css"/>
<!--<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">-->
<!-- Page content -->
<!-- section giver luft under menu -->


<h1 class="text-nowrap mb-md-4 pe-md-5"></h1>

<section class="container mt-2 mt-sm-3 py-md-3 py-lg-5">
    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="pe-xl-5">
                <div class="masonry-grid row row-cols-sm-2 row-cols-1 g-4">
                    {% include 'tilmelding/_tilmelding.html' %}
                    {% include 'tilmelding/_kort.html' %}
                <!--</div>
                <div class="masonry-grid row row-cols-sm-1 row-cols-1 g-8">-->
                    {% if user == 'anonym' %}
                    {% else %}
                        {% include 'tilmelding/_tilmeldte.html' %}
                    {% endif %}
                </div>    
            </div>
        </div>
    </div>
</section>
{% endblock app_content %}


{% block scripts %}
    {{ super() }}

    <!--<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>-->
    <script
        src="https://code.jquery.com/jquery-3.6.1.js"
        integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
        crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.4/datatables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.7/dist/autoComplete.js"></script>
    <!--<script src="{{ url_for('static', filename='js/forms-autocomplete.js') }}"></script>-->
    <!--<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script src="{{ url_for('static', filename='assets/vendor/shufflejs/dist/shuffle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/lightgallery/lightgallery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/vendor/lightgallery/plugins/video/lg-video.min.js') }}"></script>
    
    

    <script type="text/javascript">
        function reply_click(element) {
            document.getElementById('bane').value = element.getAttribute('data-product-name');
            document.getElementById('submit_1').disabled = false
        };       
        
        function clear_data(element) {
            var elements = document.getElementById("form1").elements;
            var tilmeld_flere = document.getElementById("flere").value;
            console.log(tilmeld);
                //console.log('rens data');
                for (var i = 0, element; element = elements[i++];) {
                    if (element.type === "text")
                        element.value = ''
                };
                
                console.log(tilmeld);
                if (tilmeld_flere === "0") {
                    document.getElementById('submit_1').disabled = false
                };
                
            };
        
        document.getElementById("submit_1").onclick = function () {
            add_tilmeldte();
            var aktivt_loeb = document.getElementById("loebhidden").value;
            tableActions(aktivt_loeb);
            autoAction(aktivt_loeb);
        }

        function initTable () {
                var tilmelderId = document.getElementById("deltagerhidden").value;
                var loebId = document.getElementById("loebhidden").value;
                var send = {
					konkurrence: loebId,
                    tilmelder: tilmelderId 
				};
            return jQuery('#data').DataTable( {
                    language: {
                        url: '//cdn.datatables.net/plug-ins/1.11.4/i18n/da.json'
                    },
                    destroy: true,
                    ajax: {
                        url: "{{url_for('tilmelding.get_deltagere')}}",
                        type: "GET",
                        data: send,
                        datatype: "JSON",
                        dataSrc: "data",
                        contentType: "application/json"
                    },
                    columns: [
                    {data: 'Navn'},
                    {data: 'Klub'},
                    {data: 'Bane'},
                    {data: 'Brik'}
                    ],
                });
            };

        function nyTable () {
            var table = initTable();
            };
            
        function tableActions (aktivt_loeb) { 
            setTimeout(function() {
                const tilmeld_flere = document.getElementById("flere").value;
                
                console.log("flere");
                console.log(tilmeld_flere);
                console.log(aktivt_loeb)
                if (tilmeld_flere == 0) {
                    console.log("if");
                };
                var table = initTable();
                //document.getElementById('navn').value = '';
                document.getElementById('email').value = '';
                document.getElementById('briknummer').value = '';
                document.getElementById('telefonnummer').value = '';
                document.getElementById('bane').value = '';
                document.getElementById('autoComplete1').value = '';
                document.getElementById("profileid").value = '';
                if (tilmeld_flere == 0) {
                    document.getElementById("submit_1").style.visibility = "hidden";
                    document.getElementById("submit_1").style.display = "none";
                    document.getElementById('submit_1').disabled = false;
                };
                nyTable();}, 2000);
            };

        async function autoAction (aktivt_loeb) {
            let users = await getUsers(aktivt_loeb);
            console.log("her kommer users");
            console.log(users);
            const autoCompleteJS1 = new autoComplete({
                selector: "#autoComplete1",
                wrapper: true,
                data: {
                    src: users,
                    keys: ['id','Navn'],
                    cache: true,
                },
                placeholder: "Start indtast....",
                resultItem: {
                    highlight: true,
                },
                events: {
                    input: {
                        selection: (event) => {
                            const selection = event.detail.selection.value;
                            autoCompleteJS1.input.value = selection.Navn;
                            getUserData(selection.id);  
                        }
                    }
                }
            });
        };
        
        function add_tilmeldte() {

            csfr_token = "{{ csrf_token() }}";
            loebId = document.getElementById("loebhidden").value;
            tilmelderId = document.getElementById("deltagerhidden").value;
            console.log(tilmelderId);
            console.log('tilemlderid');
            navn = document.getElementById("autoComplete1").value;
            klub = document.getElementById("klub").value;
            email = document.getElementById("email").value;
            briknummer = document.getElementById("briknummer").value;
            telefonnummer = document.getElementById("telefonnummer").value;
            tilmeldtId = document.getElementById("loberhidden").value;
            tilmeldt_status = document.getElementById("tilmeldthidden").value;
            bane = document.getElementById("bane").value;
            profilid = document.getElementById("profileid").value;
            status_profil = document.getElementById("status_profileid").value;
            flere = document.getElementById("flere").value;
            let url = "{{url_for('tilmelding.add_tilmeld1')}}";
            console.log(loebId);
            const res = fetch(url, {
                    method: "POST",
                    headers: new Headers({
                        "Content-Type": "application/json",
                        'X-CSRF-TOKEN':  csfr_token
                    }),
                    body: JSON.stringify({
                        loebId: loebId,
                        tilmelderId: tilmelderId,
                        navn: navn,
                        klub: klub,
                        bane: bane,
                        email: email,
                        briknummer: briknummer,
                        telefonnummer: telefonnummer,
                        tilmeldtId: tilmeldtId,
                        tilmeldt_status: tilmeldt_status,
                        profileid: profilid,
                        status_profilid : status_profil,
                        tilmeld_flere: flere,

                    }),
                    cache: "no-cache",
                    
                })
                .then(response => {
                        if(response.status == 200){
                            return response.json();
                        } else {
                            console.log("fejl");
                        }
                    }).then(json => {
                        console.log('Success! ' + JSON.stringify(json));
                        var tilbage = JSON.stringify(json);
                        console.log(tilbage);
                        if ( document.getElementById("deltagerhidden").value == 'Falsk') {
                            document.getElementById('deltagerhidden').value = tilbage;
                            document. getElementById('loberhidden').value = tilbage;
                        };
                        
                    }).catch(error => {
                        console.log('error with access token req!' + error);
                    });
                (document.getElementById('status_profileid').value = '');
                alert('Din tilmelding er oprettet!');
            };

        async function getUsers(aktivt_loeb) {
            //let url = "{{url_for('tilmelding.get_tilmeldte', aktivt_loeb='aktivtlob')}}".replace("aktivtlob", aktivt_loeb);
            let url = "{{url_for('tilmelding.get_alle_tilmeldte', aktivt_loeb='aktivtlob')}}".replace("aktivtlob", aktivt_loeb);
            try {
                let res = await fetch(url);
                console.log("Stig")
                console.log(res);
                return await res.json();
               
                } catch (error) {
                    console.log(error);
                }
            };

        async function getUserData(user) {
            //let url = "{{url_for('tilmelding.get_tilm_deltager', user_id='idher')}}".replace("idher", user);
            let url = "{{url_for('tilmelding.profildata', profil_id='idher')}}".replace("idher", user);
            var status_profilId = document.getElementById('status_profileid').value;
            try {
                let deltdata = await fetch(url);
                let userdata = await deltdata.json();
                document.getElementById('email').value = await userdata[0].email;
                document.getElementById('briknummer').value = await userdata[0].briknummer;
                document.getElementById('klub').value = await userdata[0].klubid;
                document.getElementById('telefonnummer').value = await userdata[0].telefonnummer;
                document.getElementById('loberhidden').value = await userdata[0].tilmeldtId;
                document.getElementById('profileid').value = await userdata[0].id;
                if (status_profilId == "Falsk") {
                    document.getElementById('status_profileid').value = await userdata[0].id;
                };
                
                //return await deltdata.json();
                //console.log(userdata);
            } catch (error) {
                console.log(error);
            }
        };

        jQuery(document).ready(function() {
            nyTable();
            var aktivt_loeb = document.getElementById("loebhidden").value;
            var taller = 0;
            //console.log('Her');
            autoAction(aktivt_loeb);
        });

    </script>
{% endblock scripts %}