app/resultater/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, IntegerField, SelectField, HiddenField, validators, RadioField, FileField
from wtforms.fields.html5 import DateField  
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length
from wtforms.ext.sqlalchemy.orm import model_form
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask_wtf.file import FileRequired
from werkzeug.utils import secure_filename
from flask_babel import _, lazy_gettext as _l
from app.models import User, konkurrence_data, Klubber, Tilmeldte, Baner, Profile


def enabled_klubber():
    AlleKlubber = Klubber.query.all()
    return AlleKlubber

#def enabled_grunddata():
#    AlleGrunddata = Grunddata.query.all()
#    return AlleGrunddata

def enabled_konkurrencer():
    AlleKonkurrencer = konkurrence_data.query.all()
    return AlleKonkurrencer

def enabled_baner():
    AlleBaner = Baner.query.all()
    return AlleBaner

class BeregnForm(FlaskForm):
    submit_1 = SubmitField('Send', id='Submit_1')

class klarmelde(FlaskForm):
    loeb = StringField('skovID')
    submit = SubmitField('Klarmeld', id='Submit')

class OpretLoeb(FlaskForm):
    skov = StringField('skov')
    klubber = SelectField('klub', choises=[('True', 'Ja')])
    dato = DateField('dato')
    type = StringField('type')
    ansvarlig = StringField('Ansvarlig')
    andet = StringField('andet')
    emitenheder = RadioField('emitenheder', choises=[('True', 'Ja'), ('False', 'Nej')])
    klarmeldt = RadioField('klarmeldt', choises=[('True', 'Ja'), ('False', 'Nej')])
    resultat = RadioField('resultat', choises=[('True', 'Ja'), ('False', 'Nej')])
    submit_1 = SubmitField('Vælg', id='submit_1')

class TilfojKort(FlaskForm):
    loeb = StringField('skovID', id='loeb')
    bane = StringField('Bane')
    beskrivelse = StringField('Beskrivelse')
    #kort = FileField(validators=[FileRequired()])
    file = FileField()
    submit = SubmitField('Vælg', id='submit')

class AdminForm(FlaskForm):
    "Opsætnings form"
    KonkurrenceType = StringField(_l('KonkurrenceType', validators=[DataRequired()]))
    Skov = StringField(_l('Skov/Navn', validators=[DataRequired()]))
    Dato = DateField(_l('Dato', validators=[DataRequired()]))
    #Path = StringField(_l('Path', validators=[DataRequired()]))
    Mappenavn = StringField(_l('Mappenavn', validators=[DataRequired()]))
    Klub = QuerySelectField(query_factory=enabled_klubber, get_label='langtnavn', 
                        allow_blank=True, blank_text=(u'Klik for at vælge'))
    #Grunddata = QuerySelectField(query_factory=enabled_grunddata, get_label='aar', 
    #                    allow_blank=True, blank_text=(u'Klik for at vælge'))
    submit = SubmitField(_l('Indsend'))


class BeregnForm(FlaskForm):
    "Beregner form"
    KonKur = QuerySelectField(query_factory=enabled_konkurrencer, get_label='mappenavn', 
                        allow_blank=True, blank_text=(u'Klik for at vælge'))
    submit = SubmitField(_l('Omform'))
    submit1 = SubmitField(_l('Tilret'))
    submit2 = SubmitField(_l('Indlæs'))
    submit3 = SubmitField(_l('Test Mail'))
    submit4 = SubmitField(_l('Test export'))

class Statistik(FlaskForm):
    form_name = HiddenField('Form Name')
    statistik = SelectField('Statistik:', choices=[('klubber', 'Klubber'), ('delt1', 'Deltager pr. bane'), ('delt2', 'Deltager pr. klub')], id='select_statistik')
    submit = SubmitField(_l('Vælg'))

class Straktider(FlaskForm):
    form_name1 = HiddenField('Form Name')
    konkurrence = SelectField('Konkurrence:', validators=[DataRequired()], id='select_konkurrence')
    bane = SelectField('Bane:', validators=[DataRequired()], id='select_bane')
    art = RadioField('Hvad:', validators=[DataRequired()], choices=[('resultat', 'Resultater'),('straktider', 'Stræktider')], default='resultat' ,id='select_type')
    submit1 = SubmitField('Vælg', id='vaelg_resultat')

class Point(FlaskForm):
    form_name2 = HiddenField('Form Name')
    banepoint = SelectField('Banepoint', validators=[DataRequired()], choices=[('Bane 1', 'Bane 1'), ('Bane 2', 'Bane 2'), ('Bane 3', 'Bane 3'), ('Bane 4', 'Bane 4'), ('Bane 5', 'Bane 5')], id='select_bane_point')
    #banepoint = SelectField('Banepoint', validators=[DataRequired()], id='select_bane_point')
    submit2 = SubmitField('Vælg Bane')
    
class brugerbaner(FlaskForm):
    form_name1 = HiddenField('Form Name')
    bruger = SelectField('Bruger:', validators=[DataRequired()], id='select_brugerbaner')
    #bane = SelectField('Bane:', validators=[DataRequired()], id='select_bane')
    #art = RadioField('Hvad:', validators=[DataRequired()], choices=[('resultat', 'Resultater'),('straktider', 'Stræktider')], default='resultat' ,id='select_type')
    #submit3 = SubmitField('Vælg Løber')

class findFil(FlaskForm):
    form_name1 = HiddenField('Form Name')
    resultat = FileField(validators=[FileRequired()])
    submit1 = SubmitField('Upload resultat fil')

class bearbejdResultatKlub(FlaskForm):
    form_name2 = HiddenField('Form Name')
    klubnavn_fil = StringField(_l('klubnavnFil'))
    klubnavn_DB = StringField(_l('klubnavnDB'))
    vurderet = SelectField('vurderet', validators=[DataRequired()], choices=[('1', 'OK'), ('2', 'Ej OK')], id='select_vurderet')
    submit2 = SubmitField('Næste Klub')

class bearbejdResultatDeltager(FlaskForm):
    form_name3 = HiddenField('Form Name')
    navn_fil = StringField(_l('navnFil'))
    navn_DB = StringField(_l('navnDB'))
    navn_tilrettet = StringField(_l('navnTilrettet'))
    #navn_valgt = RadioField('Hvad:', validators=[DataRequired()], choices=[('fil', 'Navn i fil'),('DB', 'Navn i DB'),('rettet','Til Rettet')], default='DB', id='select_type')
    navn_valgt = RadioField('Hvad:', validators=[DataRequired()], choices=[('negativ', 'Samme person?'),('fil', 'Navn i fil'),('DB', 'Navn i DB'),('rettet','Tilrettet')], default='DB', id='select_type')
    submit3 = SubmitField('Næste Navn')

class XMLStraktider(FlaskForm):
    form_name1 = HiddenField('Form Name')
    konkurrence_felt = SelectField('Konkurrence:', validators=[DataRequired()], id='select_konkurrence')
    bane = SelectField('Bane:', validators=[DataRequired()], id='select_bane')
    #art = RadioField('Hvad:', validators=[DataRequired()], choices=[('resultat', 'Resultater'),('straktider', 'Stræktider')], default='resultat' ,id='select_type')
    #submit1 = SubmitField('Vælg', id='vaelg_resultat')

class opload_resultat(FlaskForm):
    form_name = HiddenField('Form Name')
    k_felt = StringField(_l('reultat_fil'))

class tilfojGPXfil(FlaskForm):
    #loeb = StringField('skovID', id='loeb')
    loeb = SelectField('Løb:', validators=[DataRequired()], id='loeb')
    navn = StringField('navn')
    klub = StringField('klub')
    bane = StringField('bane')
    GPXfil = FileField()
    submit = SubmitField('Vælg', id='submit')

app/resultater/__init__.py
from flask import Blueprint

bp = Blueprint('resultater', __name__)

from app.resultater import routes

app/resultater/routes.py
from flask import render_template, flash, redirect, url_for, request, g, \
    jsonify, current_app, session, send_from_directory, send_file, Response
from flask_login import current_user, login_required
from app import db
from app.models import Klubber, Post, User, Profile, Tilmeldte, baneresultat, konkurrence_data, Baner, Poster 
from app.resultater import bp
#from app.resultater.controllerloeb import hent_sensteskov, hent_k, hent_klub, hentPoint, hentPointNy, hent_bruger_data, hent_statistik1, hent_statistik2, \
#    hent_statistik3, hentPointKolonner, hentPointKolonnerNy, hentStrakBane_data, hentStrakKolonner, hentResBane_data, hentResKolonnerGL, \
#        hent_bruger_kolonner, hent_ny_statistik1, hent_ny_statistik2, hent_ny_statistik3

from app.resultater.Omform import omdan
from app.resultater.resultat_helper import hentResKolonner, hentStrakKolonner, hent_klubber
from app.resultater.gpx_helper import start_gpx, map_create, map_create_flere
#from app.resultater.Navnetjek import NavneTjek
from app.resultater.forms import AdminForm, opload_resultat, tilfojGPXfil, BeregnForm, Straktider, Point, brugerbaner, Statistik, findFil, bearbejdResultatKlub, bearbejdResultatDeltager, XMLStraktider
import os
import json, codecs
import shutil
import tempfile
from pathlib import Path
#import zipfile
from zipfile import ZipFile
#from io import BytesIO
from werkzeug.utils import secure_filename
from os import listdir
import gpxpy
import gpxpy.gpx
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import haversine as hs
import datetime
import time
from datetime import date
from datetime import datetime
from datetime import timezone
import folium
from folium import plugins
import lxml
from operator import itemgetter, attrgetter
import math

plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False

UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'kmz'}

#photos = UploadSet('photos', ALL)

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@bp.route('/Base_resultater', methods=['GET', 'POST'])
def Base_resultater():
    form1 = XMLStraktider(form_name1='Straktider')
    return render_template('resultater/Base_resultater.html', form1=form1)

@bp.route('/resultater', methods=['GET', 'POST'])
def resultater():
    form1 = XMLStraktider(form_name1='Straktider')
    konkurrence1 = konkurrence_data.query.filter(konkurrence_data.konkurrenceType!='').order_by(konkurrence_data.id.desc()).first()
    #konkurrence2 = konkurrence1.pathKonkurrenceFiler
    #form1.konkurrence_felt.choices = [(str(row.id), row.konkurrence + '-' + str(row.konkurrenceDato)) for row in konkurrence_data.query.filter(konkurrence_data.konkurrenceType=='alm').order_by(konkurrence_data.id.desc()).all()]
    #form1.konkurrence_felt.choices = [(str(row.id), row.konkurrence + '-' + str(row.konkurrenceDatoStart)) for row in konkurrence_data.query.filter(konkurrence_data.konkurrenceType!='', konkurrence_data.konkurrenceDatoStart>= '2022-03-30').order_by(konkurrence_data.id.desc()).all()]
    loeb_alle = []
    loeb = {}
    #alle_loeb = [(str(row.id), row.konkurrence + '-' + str(row.konkurrenceDatoStart)) for row in konkurrence_data.query.filter(konkurrence_data.konkurrenceType!='', konkurrence_data.konkurrenceDatoStart>= '2022-03-30').order_by(konkurrence_data.id.desc()).all()]
    alle_loeb = konkurrence_data.query.order_by(konkurrence_data.konkurrenceDatoSlut.desc()).all()
    baner_alle = []
    bane_en = {}
    for lob in alle_loeb:
        loeb = {}
        loeb['id'] = int(lob.id)
        loeb['navn'] = str(lob.konkurrence) + ' ' + str(lob.konkurrenceDatoSlut)
        loeb_alle.append(loeb)
        alleBaner = Baner.query.filter(Baner.kokurrence_id==lob.id).all()
        for bane in alleBaner:
            bane_en = {}
            bane_en['id'] = bane.id
            bane_en['navn'] = str(bane.banenavn)
            baner_alle.append(bane_en)
        #with open(os.path.join(konkurrence2, "klasseListe.json"), "r") as file:
    #        manu = json.load(file)
    #        form1.bane.choices = [(i['Bane'], i['vaerdi']) for i in manu]
    
    
    #form1.bane.choices = [(row.id, row.banenavn) for row in Baner.query.filter(Baner.kokurrence_id==konkurrence1.id).all()]
    #if request.method == 'GET':
    return render_template('resultater/resultater.html', form1=form1, loeb_alle=loeb_alle, baner_alle=baner_alle)
    #return redirect('resultater.resultater')


@bp.route('/_get_XMLbaner/<konkurrence>', methods=['GET', 'POST'])
def _get_XMLbaner(konkurrence):
    konkurrence2 = request.args.get('konkurrence')
    baner = Baner.query.filter(Baner.kokurrence_id == int(konkurrence)).all()

    bane_liste = []
    for i, text in enumerate(baner):
        bearbejdet = {}
        bearbejdet[text.banenavn] = text.id
        bane_liste.append(bearbejdet)

    manu_bearb = [(i.banenavn, i.id) for i in baner]
    manu_bearb = jsonify(manu_bearb)
    baneliste = jsonify(bane_liste)
    return manu_bearb

@bp.route('/get_baner/')
def _get_baner():
    loeb = request.args.get('loeb' )
    baner = [(row.id, row.banenavn) for row in Baner.query.filter_by(kokurrence_id=int(loeb)).all()]
    return jsonify(baner)

@bp.route('/_get_XMLOtrack/', methods=['GET', 'POST'])
def _get_XMLOtrack():
    konkurrence3 = request.args.get('konkurrence')
    #konkurrence4 = konkurrence_data.query.filter(konkurrence_data.id==int(konkurrence3)).first()
    #konkurrence3 = konkurrence4.otracklink
    return jsonify(konkurrence3)

@bp.route('/test_resultat/', methods=['GET', 'POST'])
def test_resultat():
    form = opload_resultat()
    start_coords = (56.471600, 9.387841)
    #folium_map = folium.Map(location=start_coords, zoom_start=8)
    poster_loc=pd.read_csv('C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\testVirtuelResultat\\Bane2.csv')
    poster_loc['coor'] = list(zip(poster_loc.latitude, poster_loc.longitude))
    spor_loc = omdan_spor()
    m = create_map1(spor_loc,poster_loc)
    #return folium_map._repr_html_()
    return render_template('resultater/upload_resultat.html', form=form, map=m._repr_html_())
    #return render_template('resultater/upload_resultat.html', form=form) 

def create_map1(spor,poster):
    #[[56.4823463535, 9.3543324788], [56.4685664086, 9.3893127563]]
    min_lon = 9.2406334712 #west
    max_lon = 9.2728563948 #east
    min_lat = 56.4265013291 #north
    max_lat = 56.4032032384 #south
    #var imageBounds = [[56.4842893746, 9.3509591466], [56.4691528421, 9.3865768693]];
    m = folium.Map(location=[spor.latitude.mean(), spor.longitude.mean()], zoom_start=16, tiles='OpenStreetMap', width=1200, height=800)
    #kort = 'C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\testVirtuelResultat\\Canvas_2_Map.jpg'
    kort = r'C:/Users/sba/OneDrive/Dokumenter/Python40/Ny_Orientering/app/static/uploads/2022-08-03Morville/Canvas_3_Map.jpg'
    img_overlay = folium.raster_layers.ImageOverlay(image=kort, bounds=[[min_lat, min_lon], [max_lat, max_lon]])
    img_overlay.add_to(m)
    #folium.LayerControl().add_to(m)
    #poster_loc=pd.read_csv('C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\Bane2.csv')
    #poster_loc['coor'] = list(zip(poster_loc.latitude, poster_loc.longitude))
    for _, row in poster.iterrows():
        if row['status'] == 'OK':
            statuscolor='green',
        else:
            statuscolor='red',

        folium.CircleMarker(
            location= [row['latitude'],row['longitude']],
            radius=10,
            #popup= row[['Condition','Location']],
                color=statuscolor,
                fill=True,
                fill_color=statuscolor
            ).add_to(m)
    with open('C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\testVirtuelResultat\\MapRun_Bane_2_Undallslund_uge_25_i_2022_PXAC.csv', 'r') as csv_file:
        route_df = pd.read_csv(csv_file)

    coordinates = [tuple(x) for x in route_df[['latitude', 'longitude']].to_numpy()]
    folium.PolyLine(coordinates, weight=5).add_to(m)
    #m.add_children(plugins.ImageOverlay(kort, opacity=0.8, bounds =[[min_lat, min_lon], [max_lat, max_lon]]))
    return m

def omdan_spor():
    with open('C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\testVirtuelResultat\\Bane_2_Undallslund_uge_25.gpx', 'r') as gpx_file:
        gpx = gpxpy.parse(gpx_file)

    route_info = []
    for track in gpx.tracks:
        for segment in track.segments:
            for point in segment.points:
                #d = datetime.fromisoformat(point.time[:-1]).astimezone(timezone.utc)
                d = datetime.fromisoformat(str(point.time))
                timeconv = d.strftime('%H:%M:%S')
                route_info.append({
                    'latitude': point.latitude,
                    'longitude': point.longitude,
                    'time': timeconv
                })

    route_df = pd.DataFrame(route_info)

    route_df.to_csv('C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\testVirtuelResultat\\MapRun_Bane_2_Undallslund_uge_25_i_2022_PXAC.csv', index=False)

    #cust_loc=pd.read_excel('customer_location.xlsx')
    #hotel_loc=pd.read_excel("Hotel_location.xlsx")

    spor_loc=pd.read_csv('C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\testVirtuelResultat\\MapRun_Bane_2_Undallslund_uge_25_i_2022_PXAC.csv')
    #poster_loc=pd.read_csv('C:\\Users\\sba\\OneDrive\\Dokumenter\\Python40\\Ny_Orientering\\app\\static\\Bane2.csv')

    spor_loc['coor'] = list(zip(spor_loc.latitude, spor_loc.longitude))
    #poster_loc['coor'] = list(zip(poster_loc.latitude, poster_loc.longitude))

    return spor_loc

@bp.route('/_get_test_data/<loebnr>/<bane>', methods=['GET', 'POST'])
def _get_test_data(loebnr, bane):

    klasse = bane
    #if request.method == 'POST':

app/templates/resultater/_GPX_Postoversigt.html
<link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
<link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-material.css">
<link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />

<div class="masonry-grid-item col pb-1 pb-lg-5">
	<article class="card">
	  	<div class="card-body">
        <form><input type="hidden" name="csrf_token" id="csfr_token" value="{{ csrf_token() }}">
            <input type="hidden" name="banedata_id" id="banedata_id" value="{{ banedata_id }}">
            <h3 class="h4">{{ navn }} - {{ bane }} - Dine stræk. {{ konkurrencenavn }}</h3>
            <div class="card-body">
                <div id="table"></div>
                Selection:
                <span id="selectedRows">
                </span>
                <center>
                <div id="myGrid" style="height:600px; width:100%" class="ag-theme-balham"></div>
                </center>					
            </div>
          </form>
      </div>
	</article>
</div>
<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
<!--<script src="https://unpkg.com/@ag-grid-enterprise/all-modules@28.2.1/dist/ag-grid-enterprise.js"></script>-->
<script src="https://cdn.jsdelivr.net/npm/ag-grid-enterprise/dist/ag-grid-enterprise.js"></script>

<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>
<script src="{{ url_for('static', filename='js/GPXdata.js') }}"></script>

app/templates/resultater/_vis_resultater.html
<link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-grid.css">
<link rel="stylesheet" href="https://unpkg.com/ag-grid-community/dist/styles/ag-theme-material.css">
<div class="masonry-grid-item col pb-2 pb-lg-3">
	<article class="card">
	  <div class="card-body pb-2 px-10">
			<h3 class="h4">Resultater og Stræktider</h3>
			<p class="mb-4">
				<form class="row g-4 needs-validation" novalidate id="form2" method="POST" method="GET">
					<input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
					<div class="col-sm-6">
						<label for="loeb" class="form-label fs-base">Vælg løb:</label>
						<select class="form-select form-select-lg" data-customclass="form-select" id="loeb" name="loeb" required data-validate-field="loeb">
							{% for item in loeb_alle %}
							<option value="{{ item['id'] }}">{{ item['navn'] }}</option>
							{% endfor %}
						</select>
						<div class="invalid-feedback">Vælg et løb fra listen!</div>
					</div>
						<!--{{ form1.hidden_tag() }} {{ render_form(form1)}} -->
					<div class="col-sm-6">
						<label for="bane" class="form-label fs-base">Vælg Bane:</label>
						<select class="form-select form-select-lg" data-customclass="form-select" id="bane" name="bane" required data-validate-field="bane">
							{% for bane in baner_alle %}
							<option value="{{ bane['id'] }}">{{ bane['navn'] }}</option>
							{% endfor %}
						</select>
						<div class="invalid-feedback">Vælg bane!</div>
					</div>
					<button type="button" id="knap1" class="btn-orange active" aria-pressed="true" onclick="resultat()">Vis resultater</button>          <button type="button" id="knap2" class="btn-orange active" aria-pressed="true" onclick="strakNy()">Vis stræktider</button>
				</form>
				<div class="col-sm-12">
                    <div class="vertical-center">
						<div id="myGrid" style="height:600px; width:100%" class="ag-theme-balham"></div>
					</div>					
                </div>
			</p>
	  </div>
	</article>
</div>

	


{% block scripts %}
<script
    src="https://code.jquery.com/jquery-3.6.1.js"
    integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="
    crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/ag-grid-enterprise/dist/ag-grid-enterprise.js"></script>

<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>	

<script charset="utf-8" type="text/javascript">

	var dropdownval = {
			loebnr: $('#loeb'),
			bane: $('#bane'),
		};

	var loebnrorg = dropdownval.loebnr.val();
	var baneorg = dropdownval.bane.val();
	//const url1 = "/resultater/_get_resultat_koltest/"+loebnrorg+"/"+baneorg;
	//const url2 = "/resultater/_get_resultat_test/"+loebnrorg+"/"+baneorg;
	var url3 = "/resultater/_get_resultat_data/"+loebnrorg+"/"+baneorg;
	//const url3 = "/resultater/_get_grunddata/"+loebnrorg;
	
	//$.get(url3, function (data) {
	//	console.log(data);
	//	var element = document.getElementById("overskrift");
	//	tekst = data+" "+baneorg+".";
	//	element.innerHTML = tekst;
	//});

		var gridOptions = {
			rowHeight : 50,
			defaultColDef: {
				filter: false,
				cellRenderer: function(params) {
					return params.value ? params.value : '';
				},
			},
			sideBar: {
				toolPanels: [
				{
					id: 'filters',
					labelDefault: 'Filters',
					labelKey: 'filters',
					iconKey: 'filter',
					toolPanel: 'agFiltersToolPanel',
					toolPanelParams: {
					suppressExpandAll: true,
					suppressFilterSearch: true,
					},
				},
				],
				defaultToolPanel: '',
			},
		};
		
		function newGrid(url3) {
			var gridDiv = document.querySelector('#myGrid');
			var test = new agGrid.Grid(gridDiv, gridOptions);
			agGrid.simpleHttpRequest({url: url3}).then(function(data) {
				console.log(data);
				var kolonner = data[0];
				console.log(kolonner)
				gridOptions.api.setColumnDefs(kolonner);
				var raekker = data[1];
				gridOptions.api.setRowData(raekker);
			});
		};

		function recreateGrid(url3) {
			gridOptions.api.destroy();
			newGrid(url3);
		};

		function strakNy() {

			var dropdownvalstrak = {
				loebnrstrak: $('#loeb'),
				banestrak: $('#bane'),
			};
			var loebnrorgstrak = dropdownvalstrak.loebnrstrak.val();
			var baneorgstrak = dropdownvalstrak.banestrak.val();
			//const url1 = "/resultater/_get_strak_koltest/"+loebnrorgstrak+"/"+baneorgstrak;
			//const url2 = "/resultater/_get_strak_test/"+loebnrorgstrak+"/"+baneorgstrak;
			//const url3 = "/resultater/_get_grunddata/"+loebnrorgstrak;
			const url3 = "/resultater/_get_strak_data/"+loebnrorgstrak+"/"+baneorgstrak;
			

			$.get(url3, function (data) {
				console.log(data);
				var element = document.getElementById("overskrift");
				tekst = data+" "+baneorgstrak+".";
				element.innerHTML = tekst;
			});
			
			recreateGrid(url3);
		};

		function resultat() {

			dropdownvalresultat = {
				loebnrresultat: $('#loeb'),
				baneresultat: $('#bane'),
			};
			var loebnrorgresultat = dropdownvalresultat.loebnrresultat.val();
			var baneorgresultat = dropdownvalresultat.baneresultat.val();
			//const url1 = "/resultater/_get_resultat_koltest/"+loebnrorgresultat+"/"+baneorgresultat;
			//const url2 = "/resultater/_get_resultat_test/"+loebnrorgresultat+"/"+baneorgresultat;
			const url3 = "/resultater/_get_resultat_data/"+loebnrorgresultat+"/"+baneorgresultat;
			//const url3 = "/resultater/_get_grunddata/"+loebnrorgresultat;
			

			$.get(url3, function (data) {
				console.log(data);
				var element = document.getElementById("overskrift");
				tekst = data+" "+baneorgresultat+".";
				element.innerHTML = tekst;
			});

			recreateGrid(url3);
			};

		//setup the grid after the page has finished loading
		document.addEventListener('DOMContentLoaded', function() {
			var dropdownvalresultat = {
				loebnrresultat: $('#loeb'),
				baneresultat: $('#bane'),
			};
			var loebnrorgresultat = dropdownvalresultat.loebnrresultat.val();
			var baneorgresultat = dropdownvalresultat.baneresultat.val();
			newGrid(url3);
		});


    $(function() {
    
        // jQuery selection for the 2 select boxes
        var dropdown = {
            loeb: $('#loeb'),
            baner: $('#bane')
        };
    
        // call to update on load
        updateCounties();
    
        // function to call XHR and update county dropdown
        function updateCounties() {
            var send = {
                loeb: dropdown.loeb.val()
            };
            dropdown.baner.attr('disabled', 'disabled');
            dropdown.baner.empty();
            $.getJSON("{{ url_for('resultater._get_baner') }}", send, function(data) {
                data.forEach(function(item, index) {
                    console.log(item);
                    dropdown.baner.append(
                            $('<option>', {
                                value: item[0],
                                text: item[1]
                            })
                    );

                    if (index = 0) {
                        console.log(item);
                        updateBaner(item[0]);
                        }
                })
                dropdown.baner.removeAttr('disabled');
            });
        };
    
        // event listener to state dropdown change
        dropdown.loeb.on('change', function() {
            updateCounties();
        });
    
    });


	//document.addEventListener('DOMContentLoaded', function() {
	//	const url3 = "/resultater/_get_strak_data/"+loebnrorg+"/"+baneorg;
	//	newGrid(url3);
	//});
</script>



{% endblock scripts %}

	